import { readFileSync, writeFileSync } from "node:fs";

/**
 * Copies the daybook's drawing module into the site's MCP Apps view.
 *
 * Claude chat draws that view in a frame that fetches nothing, so the module
 * goes in as a string. `plugins/daybook/ui/daybook.js` stays the only source:
 * run this after changing it. The build runs it with `--check`, which fails
 * when the copy has drifted, since this repository has no test runner.
 *
 * Paths are relative to apps/web, where pnpm runs the web package's scripts.
 */

const SOURCE = "../../plugins/daybook/ui/daybook.js";
const TARGET = "src/lib/mcp/views/daybook-ui.ts";

function generate(js: string): string {
  // The view puts this inside a script element, which the first closing tag
  // or comment opener would end early, whatever quotes surround it.
  if (/<\/script/i.test(js)) throw new Error(`${SOURCE} contains a closing script tag`);
  if (js.includes("<!--")) throw new Error(`${SOURCE} contains an HTML comment opener`);
  const line = js.split("\n").findIndex((l) => /[^\x00-\x7f]/.test(l));
  if (line >= 0) throw new Error(`${SOURCE} line ${line + 1} is not ASCII; write the character as an escape`);
  const body = js.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  return [
    "// Generated by scripts/daybook-ui.ts from plugins/daybook/ui/daybook.js.",
    "// Do not edit; edit the module and run `pnpm --filter web daybook-ui`.",
    "",
    `export const DAYBOOK_UI_JS = \`${body}\`;`,
    "",
  ].join("\n");
}

async function main() {
  const out = generate(readFileSync(SOURCE, "utf8"));
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(TARGET, "utf8");
    } catch {}
    if (current !== out) {
      console.error(`${TARGET} is out of date with ${SOURCE}. Run pnpm --filter web daybook-ui and commit both.`);
      process.exit(1);
    }
    console.log(`${TARGET} matches ${SOURCE}.`);
    return;
  }
  writeFileSync(TARGET, out);
  console.log(`Wrote ${TARGET}.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
